### ISSUE TITLE
Feature Requests , i want ...

### ISSUE THREAD

**Issue by pkptzx** [ohsayan/jotsy#11]
`del/merge/group notes`:
operation like [Collections in Microsoft Edge](https://support.microsoft.com/en-us/microsoft-edge/organize-your-ideas-with-collections-in-microsoft-edge-60fd7bba-6cfd-00b9-3787-b197231b507e)

`search`
`modify`
`paste image` : and auto save to server
`pagination`
`tag/label management`

`(frontend)edit auto height`

`exports/export zip(markdown and res)/pdf`

~~`public`: customer specify note public access , like blog~~

`other`:
~~plugin mechanism: above implement by plugin~~
OS tool: mouse select text/image... right click send to jotsy.(config token or login)

**Comment by ohsayan** [comment]
I'll go through all that as soon as I can :)
