### ISSUE TITLE
[BUG] The Jotsy hosted demo is down

### ISSUE THREAD

**Issue by adnankattekaden** [ohsayan/jotsy#15]
**https://jotsy.skytable.io/  is not working**

**To Reproduce**

**Comment by ohsayan** [comment]
Acknowledging this. During our last server migration the demo's data wasn't restored properly (a docker image) and hence this has been down for a considerable while.

**Comment by ohsayan** [comment]
Fixing this now. Sorry for the delay

**Comment by ohsayan** [comment]
Can you [try and use the new site here](https://jotsy.sayan.blog)?

**Comment by ohsayan** [comment]
This has been fixed. Please re-open if you have any trouble :)
