### ISSUE TITLE
[BUG] jotsy-app container fails to start

### ISSUE THREAD

**Issue by varens** [ohsayan/jotsy#16]
**Describe the bug**

Having followed the steps in README, the app container fails to run.
`docker compose logs` says:
```
jotsy-app-1  | Error: SkyError(ParseError)
jotsy-skydb-1  | [2022-11-04T11:52:46Z INFO  skyd] Skytable v0.8.0 | https://github.com/skytable/skytable
jotsy-skydb-1  | [2022-11-04T11:52:46Z INFO  skyd] Using settings from supplied configuration
jotsy-skydb-1  | [2022-11-04T11:52:46Z WARN  skyd::config::feedback] CLI warnings: Running in `user` mode. Set mode to `prod` in production
jotsy-skydb-1  | [2022-11-04T11:52:46Z INFO  skyd::dbnet::listener] Server started on skyhash://0.0.0.0:2003
jotsy-skydb-1  | [2022-11-04T11:52:46Z ERROR skyd::dbnet::tcp] Error: connection reset
jotsy-skydb-1  | [2022-11-04T11:52:46Z ERROR skyd::dbnet::tcp] Error: connection reset
```

`docker container ls`:
```
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS                           PORTS                                   NAMES
5d6e165da23e   ohsayan/jotsy:latest   "jotsy"                  28 minutes ago   Exited (1) 28 minutes ago                                                jotsy-app-1
385b8a9cfa54   skytable/sdb:latest    "skyd --noart -h 0.0…"   28 minutes ago   Up 28 minutes                    127.0.0.1:2003->2003/tcp                jotsy-skydb-1
```

**To Reproduce**

1. Run `mkdir jotsy && cd jotsy && wget https://raw.githubusercontent.com/ohsayan/jotsy/next/docker-compose.yml && sudo docker-compose up -d`
2. Interrogate the Docker service

**Expected behavior**

jotsy-app container initiates and runs

**Meta (please complete the following information):**
 - OS: Fedora 36
 - Version/Commit hash: Tag latest, digest 79b6657e2fc1

**Comment by ohsayan** [comment]
Acknowledging error. This is likely due to the latest Skytable version using the new protocol. We'll pin the current one to 0.7. Thanks for raising this.

**Comment by ohsayan** [comment]
Can you please verify if it works for you now? If not, please feel free to re-open :)

**Comment by varens** [comment]
Yep, sure does.
Thank you for looking into it so quickly.
